AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Anomaly Detector - Parallel Weather Anomaly Detector

Globals:
  Function:
    Runtime: python3.11
    Timeout: 60
    MemorySize: 128

Resources:

  AnomalyDetectorWorker:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: AnomalyDetectorWorker
      CodeUri: worker/
      Handler: app.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: Anomaly_Detector_Results
        - S3CrudPolicy:
            BucketName: anomaly-detector-dashboard

  AnomalyDetectorCoordinator:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: AnomalyDetectorCoordinator
      CodeUri: coordinator/
      Handler: app.lambda_handler
      Policies:
        - LambdaInvokePolicy:
            FunctionName: AnomalyDetectorWorker
      Events:
        DailySchedule:
          Type: Schedule
          Properties:
            Schedule: cron(0 12 * * ? *)
            Description: Run Anomaly Detector every morning at 8 AM Eastern
            Enabled: true